// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CommonUser struct {
	ID        int64              `json:"id"`
	FullName  string             `json:"full_name"`
	Cpf       string             `json:"cpf"`
	Email     string             `json:"email"`
	CreatedAt time.Time          `json:"created_at"`
	Cnpj      pgtype.Text        `json:"cnpj"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
