// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateCommonUser(ctx context.Context, arg CreateCommonUserParams) (CommonUser, error)
	GetCommonUser(ctx context.Context, id int64) (CommonUser, error)
	GetCommonUserByEmail(ctx context.Context, email string) (CommonUser, error)
}

var _ Querier = (*Queries)(nil)
